### ISSUE TITLE
Sustainability

### ISSUE THREAD

**Issue by becarpenter** [becarpenter/book6#62]
Is there anything sensible we can say about IPv6 and energy consumption?

**Comment by cron2** [comment]
There have been claims that IPv6 saves on energy consumptions, presumably because devices behind a NAT do no longer have to send packets frequently to keep the NAT state in place.

OTOH with stateful firewalls now being the default, this no longer applies.

Also, there've been quite a few problems with mobile devices going to sleep and missing multicast RAs, thus loosing their IPv6 connectivity while sleeping - which more a counterargument.

I think the most sensible thing to say is "no significant difference in energy consumption expected between IPv4 and IPv6"

**Comment by becarpenter** [comment]
Have a look at https://github.com/becarpenter/book6/blob/main/6.%20Management%20and%20Operations/Energy%20consumption.md and please comment.

**Comment by becarpenter** [comment]
Closed as done for now. If anything relevant comes out of the IETF discussion we can add text later.
