### ISSUE TITLE
Line length

### ISSUE THREAD

**Issue by jenslink** [becarpenter/book6#65]
As I'm using  (neo)vim in the terminal for most of my work, including reading most markdown files, 
and having https://github.com/markdownlint/markdownlint integrated into the vim config the 
overly long line annoy me. Would it be okay, to break the lines so that markdownlint stops complaining? 

I do the work, I just want to know if that's okay with you. 

Jens

**Comment by becarpenter** [comment]
There seem to be some differences in the way various md processors deal with text that includes line breaks. Maybe there's even a bit of Linux vs Windows in there too. So I don't want to just say "yes" without understanding the consequences. Where would you want the line break and does it have to be a simple LF? And what about really long URLs?

**Comment by jenslink** [comment]
markdownlint, like most other linters, says 80 characters per line. In my own files
I ignore this hard limit sometimes, e.g., with long URLs. It should not break anything. 

As a workaround, I did remember that I can set the following commands in vim, which make the text at least readable, but editing is still no fun.

```
set wrap 
set linebreak 
```

**Comment by becarpenter** [comment]
I think the cleanest fix for this will be if I add line wrapping to the makebook program. That way we can ensure that authors don't have to worry about this and that URLs, code, etc. never get broken. Any objection to doing it at 72 instead of 80? It's traditional, and should avoid messing up any text extracted from .txt versions of RFCs, which historically wrap at 72.

(I think all I'll need to do is code a Python function called wrapline() and stick that in the right place in my existing code. Or find a Python library that can do it.)

**Comment by jenslink** [comment]
https://github.com/executablebooks/mdformat might do the trick. 

Just tired  ```mdformat --wrap 72 Addresses.md``` and the results look good. It also cleaned up some other 
stuff markdown lint complained about. 

https://github.com/jenslink/book6/blob/main/2.%20IPv6%20Basic%20Technology/Addresses.md
https://raw.githubusercontent.com/jenslink/book6/main/2.%20IPv6%20Basic%20Technology/Addresses.md

**Comment by becarpenter** [comment]
Good news, it looks very easy to integrate mdformat in my makebook code. Two lines of Python in fact:
```
import mdformat
...
mdformat.file(filepath, options={"wrap":72})
```
I want to do a few more tests checking for corner cases, but it seems worth doing that.

**Comment by becarpenter** [comment]
I'm very impressed by mdformat, it seems to do everything right. I have a new version of makebook that (a) applies mdformat to every file that it needs to rewrite to disk for any reason and (b) has a pro option to run mdformat on every file in the whole book. I've tested it on a spare copy of the book and it seems  all good, but it's a bit late in my day here so I won't run it on the live copy until tomorrow, after I've caught up on outstanding PRs. Watch out for a massive commit after I do that!
(I also had to fix a tricky problem in the existence check for RFCs, BCPs, etc since something in the SSL area had changed on the RFC Editor site. That took more time than adding mdformat.)

**Comment by becarpenter** [comment]
OK, I ran mdformat on _everything_ which worked well except for Contents.md which got messed up (now fixed manually), and exempted from mdformat for the future). From now on it will run automatically on any of the main text .md files that are modified by a run of the makebook program.
